name: main
on:
  push:
    branches:
      - main

jobs:
  upload-gh-pages:
    runs-on: squidfunk/mkdocs-material:9.0.6
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Generate HTML
        run: |
          pip3 install -r requirements.txt
          cd docs
          mkdocks build
      - name: push gh-pages
        run: |
          cd docs 
          mkdocs gh-deploy --force