name: main
on:
  push:
    branches:
      - main

jobs:
  upload-gh-pages:
    #    runs-on: squidfunk/mkdocs-material:9.0.6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - name: Setup Pages
#      - uses: actions/configure-pages@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
#      - name: Checkout
#        uses: actions/checkout@v3
      - name: Setup code
        run: pip3 install -r requirements.txt
#      - name: Generate HTML
#        run: |
#          cd docs
#          mkdocs build
      - name: push gh-pages
        run: |
          cd docs 
          mkdocs gh-deploy --force